server:
  port: 8763
eureka:
  instance:
    hostname: eureka-zb
  client:
    region: chongqing
    availability-zones:
      chongqing: zb,sc,tc
    service-url:
      sc: http://eureka-sc:8761/eureka/
      tc: http://eureka-tc:8762/eureka/
      zb: http://eureka-zb:8763/eureka/