server:
  port: 8762
eureka:
  instance:
    hostname: eureka-tc
  client:
    region: chongqing
    availability-zones:
      chongqing: tc,sc,zb
    service-url:
      sc: http://eureka-sc:8761/eureka/
      tc: http://eureka-tc:8762/eureka/
      zb: http://eureka-zb:8763/eureka/